"""Init services tree

Revision ID: 4621497055f4
Revises: 
Create Date: 2024-02-10 12:52:12.582381

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "4621497055f4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
